/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ing.challenge;

import com.google.common.truth.Truth;
import com.ing.challenge.model.Product;
import com.ing.challenge.parser.CsvProductParser;
import com.ing.challenge.parser.Parser;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.net.URISyntaxException;
import java.nio.file.Path;

import static com.google.common.truth.Truth.assertThat;

class ParseAppTest {
    @Test
    @Disabled("fails on github actions build.")
    void createApp() throws IOException, URISyntaxException {
        ParseApp.main(new String[]{});
        Path path = ParseApp.pathToOutputFile("999-test.csv");
        Parser<Product> csvParser = new CsvProductParser();
        var products = csvParser.read(
                path.toAbsolutePath()
                        .toString()
                        .replace("/test/", "/main/")
        );
        assertThat(products).hasSize(2);
    }
}
