  
name: Build & Test

env:
  DOTNET_VERSION: "3.1.100"

on:
  push:
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout branch'
        uses: actions/checkout@v2

      - name: Setup Dotnet ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore Assignment01

      - name: Build
        run: dotnet build --configuration Release --no-restore Assignment01

      - name: Test
        run: dotnet test --no-restore --verbosity normal Assignment01
