/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ing.challenge;

import com.ing.challenge.converter.ProductConverter;
import com.ing.challenge.model.Product;
import com.ing.challenge.parser.CsvProductParser;
import com.ing.challenge.parser.Parser;
import org.jetbrains.annotations.NotNull;

import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;

public class ParseApp {

    public static void main(String[] args) throws URISyntaxException, IOException {
        Path source = pathToOutputFile("999-test.csv");
        Parser<Product> csvParser = new CsvProductParser();
        ProductConverter converter = new ProductConverter();
        List<Product> products = csvParser.read(getFile("001-experts-inputs.csv"));
        List<Product> filteredProducts = products.stream().filter(p -> converter.filterPrice(p,10.0))
                .map(p -> converter.convertCurrency(p,0.85))
                .collect(Collectors.toList());
        File f = Files.createFile(source).toFile();
        csvParser.write(f, filteredProducts);
    }

    protected static Path pathToOutputFile(String fileName) throws IOException {
        var source = Paths.get(ParseApp.class.getResource("/").getPath(),fileName);
        if(Files.exists(source)) {
            Files.delete(source);
        }
        return source;
    }

    @NotNull
    protected static File getFile(String fileName) throws URISyntaxException {
        return Path.of(
                Objects.requireNonNull(ClassLoader
                        .getSystemClassLoader()
                        .getResource(fileName))
                        .toURI()
        ).toFile();
    }
}
