name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  configuration: ${{ 'Release' }}
  project: ${{ 'Src/TwIngC1.csproj' }}
  testProject: ${{ 'Tst/TwIngC1.Tests.csproj' }}
  versionMajor: ${{ '1' }}
  versionMinor: ${{ '0' }}
  versionPatch: ${{ github.run_number }}
  version: '${{ versionMajor }}.${{ versionMinor }}.${{ versionPatch }}'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore $(project)
      working-directory: c1
    - name: Build
      run: dotnet build $(project) --configuration $(Configuration) --no-restore /p:AssemblyVersion=$(version) /p:Version=$(version)
      working-directory: c1
    - name: Test
      run: dotnet test $(testProject) --no-build --verbosity normal --configuration $(configuration) /p:AssemblyVersion=$(version)  --collect "Code coverage" /p:Version=$(version) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
      working-directory: c1
    - name: Publish
      run: dotnet publish $(project) --no-build --configuration $(Configuration) --output publishOutput
      working-directory: c1
    - name: Upload DotNet Console App
      uses: actions/upload-artifact@v2
      with:
        name: console
        path: c1/publishOutput
