name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  configuration: ${{ 'Release' }}
  project: ${{ 'Src/TwIngChallenge.csproj' }}
  runtime: ${{ 'win-x64' }}
  testProject: ${{ 'Tst/TwIngChallenge.Tests.csproj' }}
  version: ${{ '1.0.0' }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    # - name: Install GitVersion
    #   uses: gittools/actions/gitversion/setup@v0.9.4
    #   with:
    #     versionSpec: '5.3.x'
    # - name: Use GitVersion
    #   id: gitversion # step id used as reference for output values
    #   uses: gittools/actions/gitversion/execute@v0.9.4
    # - name: Setup .NET Core
    #   uses: actions/setup-dotnet@v1
    #   with:
    #     dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ${{ env.project }} --runtime ${{ env.runtime }}
    - name: Build
      run: dotnet build ${{ env.project }} --configuration ${{ env.configuration }} --runtime ${{ env.runtime }} --no-restore /p:AssemblyVersion=${{ env.version }} /p:Version=${{ env.version }}
    - name: Test
      run: dotnet test ${{ env.testProject }} --no-build --verbosity normal --configuration ${{ env.configuration }} /p:AssemblyVersion=${{ env.version }}  --collect "Code coverage" /p:Version=${{ env.version }} /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
    - name: Publish
      run: dotnet publish ${{ env.project }} --no-build --configuration ${{ env.configuration }} --runtime ${{ env.runtime }} --output publishOutput
    - name: Upload DotNet Console App
      uses: actions/upload-artifact@v2
      with:
        name: console
        path: publishOutput
      if:
        contains('
          refs/heads/main
        ', github.ref)
      
