name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  configuration: ${{ 'Release' }}
  project: ${{ 'Src/TwIngC1.csproj' }}
  testProject: ${{ 'Tst/TwIngC1.Tests.csproj' }}
  versionMajor: ${{ '1' }}
  versionMinor: ${{ '0' }}
  versionPatch: ${{ github.run_number }}

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      version:   '${{ env.versionMajor }}.${{ env.versionMinor }}.${{ env.versionPatch }}'
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore $(project)
      working-directory: c1
    - name: Build
      run: dotnet build $(env.project) --configuration $(env.configuration) --no-restore /p:AssemblyVersion=$(env.version) /p:Version=$(env.version)
      working-directory: c1
    - name: Test
      run: dotnet test $(env.testProject) --no-build --verbosity normal --configuration $(env.configuration) /p:AssemblyVersion=$(env.version)  --collect "Code coverage" /p:Version=$(env.version) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
      working-directory: c1
    - name: Publish
      run: dotnet publish $(env.project) --no-build --configuration $(env.Configuration) --output publishOutput
      working-directory: c1
    - name: Upload DotNet Console App
      uses: actions/upload-artifact@v2
      with:
        name: console
        path: c1/publishOutput
