name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  configuration: Release
  solution: c.sln
  project: Src/TwIngChallenge.csproj
  runtime: win-x64
  testProject: Tst/TwIngChallenge.Tests.csproj

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.4
      with:
        versionSpec: '5.3.x'
    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ${{ env.solution }} --runtime ${{ env.runtime }}
    - name: Build
      run: dotnet build ${{ env.project }} --configuration ${{ env.configuration }} --runtime ${{ env.runtime }} /warnaserror --no-restore /p:AssemblyVersion=${{ steps.gitversion.outputs.majorMinorPatch }} /p:Version=${{ steps.gitversion.outputs.majorMinorPatch }}
    - name: Test
      run: dotnet test ${{ env.testProject }} --no-restore --verbosity normal --configuration ${{ env.configuration }} /p:AssemblyVersion=${{ steps.gitversion.outputs.majorMinorPatch }}  --collect "Code coverage" /p:Version=${{ steps.gitversion.outputs.majorMinorPatch }} --collect "XPlat Code Coverage"
    - name: Publish
      run: dotnet publish ${{ env.project }} --no-build --configuration ${{ env.configuration }} --runtime ${{ env.runtime }} --output publishOutput
    - name: XUnit Viewer
      id: xunit-viewer
      uses: AutoModality/action-xunit-viewer@v1  
    - name: Attach the report
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.xunit-viewer.outputs.report-name }}
        path: ${{ steps.xunit-viewer.outputs.report-dir }}
    - name: Publish Code Coverage Results
      uses: 5monkeys/cobertura-action@master
      with:
        path: TestResults/**/coverage.cobertura.xml
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        minimum_coverage: 75
    - name: Upload DotNet Console App
      uses: actions/upload-artifact@v2
      with:
        name: console
        path: publishOutput
      if:
        contains('
          refs/heads/main
        ', github.ref)
      
